service: serverless-lambda-chrome
frameworkVersion: "1.60.5"

provider:
  name: aws
  timeout: 30
  memorySize: 1536
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  environment:
    IS_OFFLINE: ${opt:offline}
  apiGateway:
    binaryMediaTypes:
      - "application/pdf"
plugins:
  - serverless-webpack
  # - serverless-domain-manager
  - serverless-offline

layers:
  HeadlessChrome:
    name: HeadlessChrome
    compatibleRuntimes:
      - nodejs12.x
    description: Required for headless chrome
    package:
      artifact: layers/chrome_aws_lambda.zip
custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - chrome-aws-lambda
    packager: "yarn"

  serverless-offline:
    location: .webpack/service

  # customDomain:
  #   domainName: labs.mianio.com
  #   basePath: demo
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true

functions:
  generate-the-pdf:
    # provisionedConcurrency: 2
    handler: src/pdf.generate
    layers:
      - { Ref: HeadlessChromeLambdaLayer }
    events:
      - http:
          path: pdf
          method: get
          cors: true
