service: pdf
frameworkVersion: "3.23.0"

provider:
  name: aws
  profile: usercentric
  timeout: 30
  memorySize: 1526
  runtime: nodejs16.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  apiGateway:
    binaryMediaTypes:
      - "application/pdf"
plugins:
  - serverless-webpack
  # - serverless-domain-manager
  - serverless-offline
  - ./src/lib/offline-invalidate

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceInclude:
        - "@sparticuz/chromium"
        - "puppeteer-core"
    packager: "yarn"

  serverless-offline:
    location: .webpack/service

  # customDomain:
  #   domainName: pdf.usercentric.com.au
  #   basePath: dev
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true

functions:
  generate-the-pdf:
    handler: src/pdf.default
    events:
      - http:
          path: pdf
          method: get
          cors: true
