version: 2.1
# orbs:
  # node: circleci/node@2.0.2
  # slack: circleci/slack@3.4.2
  # serverless-framework: circleci/serverless-framework@1.0.1
  # aws-cli: circleci/aws-cli@1.3.0

jobs:
  build:
    docker:
      - image: circleci/node:12.18.2

    working_directory: ./

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            yarn install
            yarn serverless config credentials --provider aws --key ${awsKey} --secret ${awsSecret} --profile usercentric

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
        
      # run tests!
      - run: 
          name: Run tests with coverage
          command: npm test --coverage

      - run:
          name: Deploy application
          command: yarn deploy_dev