version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  serverless-framework: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@1.3.0

jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: pdf-lambda
          org-name: circleci
      - run:
          command: npm run deploy
          name: deploy
  deploy-dev:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: pdf-lambda
          org-name: circleci
      - run:
          command: npm run deploy_dev
          name: deploy_dev

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
              branches:
                only:
                  - master
      - deploy-dev:
          filters:
              branches:
                only:
                  - develop
