version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: circleci/node:12.18.2

    working_directory: ~/repo

    steps:
      - slack/notify:
          message: 'Pdf-lambda build started'
          webhook: '${SLACK_WEBHOOK}'
          
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            yarn install
            yarn serverless config credentials --provider aws --key ${awsKey} --secret ${awsSecret} --profile usercentric

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
        
      - run: 
          name: Run tests
          command: npm test
      
      # deploy dev
      - when:
          condition:
            equal: [ develop, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Deploy dev
                command: yarn deploy_dev
      
      # deploy prod
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Deploy prod
                command: yarn deploy_prod
      
      # slack notification
      - slack/status:
          failure_message: ':red_circle: PDF-lambda deployment failed!'
          success_message: ':tada: PDF-lambda deployment succeeded!'
          webhook: '${SLACK_WEBHOOK}'
